// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuD-e4QHABpWEMsMhWyTQkDsSFkeoDgzU',
    appId: '1:849791567663:web:3f5b3eae8e50b413a083da',
    messagingSenderId: '849791567663',
    projectId: 'fooddeliveryapp-7372c',
    authDomain: 'fooddeliveryapp-7372c.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-7372c.appspot.com',
    measurementId: 'G-B1YYH1K8S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-aUluycDu1_DexhpFUZC9pOvpyGRionI',
    appId: '1:849791567663:android:51b3e1a2dab6e544a083da',
    messagingSenderId: '849791567663',
    projectId: 'fooddeliveryapp-7372c',
    storageBucket: 'fooddeliveryapp-7372c.appspot.com',
  );
}
